language: ruby
rvm:
- 2.3
- 2.4
- 2.5
script:
- bundle exec rspec
notifications:
  slack:
    secure: X5ENcwG/TTEjEi8hfhmX8Y0NMJPh4oUEEOOzR3XuPZ6NgnHIVxxLhSa+kqHrx7QwYx7YRUayLhhXst1n7fBOHdTpidvGZwLJnr6REnFNgwcevhFly6+o5dA5BpZPji3YQD3esTLfSDec29iG6Y19M2mrGSZFjsZR7PAcVpCs5Qj6Te45jpnH7gm57xsQUorpFJMi+Zm+O68VxwiMoiMcr/BvMidsMJxeGcdqZUCnXN4QTQvSKDTy0Uugpoavw0sceokZDjEirLKGluXAJUb5ovtRE0tgkp2Ruj4mk6gRljHwHxaDZ9dlkbbgtW1wSRrbP3VzHKNcIVrUN505bRV3yOddEmF0iP49cykTPIxLCSzqV3TPA+wgSfP0f11olFczTEo8KCuxAjV+wfG5XZjiTRMXMglCLuw1MpuSfcehRwahCYQzejGmXR7tzKLmtUJZE1LmziHqVCW3KVs3AaiwILNXm3InzO1vjCQX/AzBzP/SPiQnlwtUZtXSQglfmQadjJhFYsR+NKXbVJJlQlgYUEtRZ9lQHvU+sYLz+nLHv0HpGDz+/Z2UIkqB1o/ySFEatHShHftzEUC0PJ7lIqEnYZ3twWhbX1P7r+4F6eZnk8WXFvV+fCBrNM8tHBR1kBACnW6OlS9ROTFb6slknQE1oc/SWiHeZMC+tgAnR4QAl1I=
