language: ruby
rvm:
- 2.3
- 2.4
- 2.5
script:
- bundle exec rspec
notifications:
  slack:
    secure: bvLSk8zPPWHadhXNyckezP0gzZJJHMwoC13JS5R3I2+K0NGjyinR4TNQEZDbzDKvWSvogF5zp+fY+adokUXN1TNpY3dg2uZxAEEa9+YpES2BQQsM+uQvDmUMimmrvmQB64BiNpR9u6TiAifYkSqUllLvxI210W3HZBQ7uzPzsPNitT0xsaja81fJtCiiKIuzzjngSXiA/dRfI87FT55gjx/AAB8FizeHcMx2s2yfOM4Htk5d4ocEouF5IqIjaqs/lqMky8uWdOLGGOy8eQ53A47XlUMkrmsQAUJ0RC3j0VnYxj8+SSwQtcKQepKwqlZRutpZI2mpJzeGGNO9qJCZQgnBfMsq5gJ1+H4iryAJ7UhtnkdG9f64+/3AZyvtOUrA8RgEjTWYIl97IjZJpWz+1NK0pUDbU7d/BGIwr8PzHdUF42VSWTbkFq2DuhXVZS+174fZFUayf5ayp2UBcTXBV8Big93+rWAz76ROHJzxykwZdDxxalrEMRbMm+GAf0/aPRjytBZ8klQA4ltP/K+/I8juFe7kf5E32wjKHjc8V/gzrNooCf2vfqHFp9u1+nvqokTu4+Qofeb9w2ou+l1qOtoL4wyLtHFChhVev792ab4sEuGCvhgBmSKZhYnvTPvCfP9kIlxG9gXc3myZqBvA46ad2LxeF+cbuuL2SRq86g4=
